## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [1]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-06-29 15:45:39--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: 'input.txt'

input.txt           100%[===================>]   1.06M  5.53MB/s    in 0.2s    

2024-06-29 15:45:39 (5.53 MB/s) - 'input.txt' saved [1115394/1115394]



In [2]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [3]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [4]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [20]:
# create a mapping from characters to integers

stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda l: "".join([itos[i] for i in l])

In [21]:
print(encode("hello"))

[46, 43, 50, 50, 53]


In [23]:
print(decode(encode("hello")))

hello


In [28]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch

print(f"No. of chars: {len(text)}")
print(f"No. of encoded integers: {len(encode(text))}") # => 1115394; 
assert len(text)==len(encode(text)) #this confirms our ecoder is working fine


No. of chars: 1115394
No. of encoded integers: 1115394


In [32]:
encoded_text = encode(text)
data = torch.tensor(encoded_text, dtype=torch.long)

print(data.shape, data.dtype)

print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [56]:
# Let's now split up the data into train and validation sets
# first 90% will be train, rest val
print(f"Data Size: {len(data)}")
n = int(len(data)*0.9)

print(f"90%: {len(data[:n])}| 10%: {len(data[n:])}")

print(f"90%: {len(data[:n])} + 10%: {len(data[n:])} =  {len(data[:n]) + len(data[n:])}")
assert len(data[:n]) + len(data[n:]) == len(data)


train_data = data[:n]
val_data = data[n:]

Data Size: 1115394
90%: 1003854| 10%: 111540
90%: 1003854 + 10%: 111540 =  1115394


In [57]:
block_size = 8 # also known as context length, that a transformer see

train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [75]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

print(f"input context-> target")
print("="*50)

for t in range(block_size):    
    print(f"{x[:t+1]} -> {y[t]}")

input context-> target
tensor([18]) -> 47
tensor([18, 47]) -> 56
tensor([18, 47, 56]) -> 57
tensor([18, 47, 56, 57]) -> 58
tensor([18, 47, 56, 57, 58]) -> 1
tensor([18, 47, 56, 57, 58,  1]) -> 15
tensor([18, 47, 56, 57, 58,  1, 15]) -> 47
tensor([18, 47, 56, 57, 58,  1, 15, 47]) -> 58


In [87]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    data = train_data if split=='train' else val_data
    
    # This line generates batch_size random indices (ix) within the range from 0 to len(data) - block_size. 
    # The subtraction by block_size ensures there’s enough room to create sequences of length block_size.
    ix = torch.randint(low=0, high=len(data)-block_size, size=(batch_size,)) # we get batch_size random integers within the range
    
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    
    return x,y

In [88]:
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----


In [90]:
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b,:t+1]
        target = yb[b, t]
        
        print(f"when the input is: {context.tolist()}, the target is: {target}")

when the input is: [24], the target is: 43
when the input is: [24, 43], the target is: 58
when the input is: [24, 43, 58], the target is: 5
when the input is: [24, 43, 58, 5], the target is: 57
when the input is: [24, 43, 58, 5, 57], the target is: 1
when the input is: [24, 43, 58, 5, 57, 1], the target is: 46
when the input is: [24, 43, 58, 5, 57, 1, 46], the target is: 43
when the input is: [24, 43, 58, 5, 57, 1, 46, 43], the target is: 39
when the input is: [44], the target is: 53
when the input is: [44, 53], the target is: 56
when the input is: [44, 53, 56], the target is: 1
when the input is: [44, 53, 56, 1], the target is: 58
when the input is: [44, 53, 56, 1, 58], the target is: 46
when the input is: [44, 53, 56, 1, 58, 46], the target is: 39
when the input is: [44, 53, 56, 1, 58, 46, 39], the target is: 58
when the input is: [44, 53, 56, 1, 58, 46, 39, 58], the target is: 1
when the input is: [52], the target is: 58
when the input is: [52, 58], the target is: 1
when the input i